# Generated by Django 3.2 on 2022-11-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0, verbose_name='العمر'),
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(default='', max_length=200, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='person',
            name='area',
            field=models.CharField(default='', max_length=200, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='person',
            name='direction',
            field=models.CharField(default='', max_length=200, verbose_name='التوجه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gov',
            field=models.CharField(default='', max_length=200, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nkown_person',
            field=models.CharField(default='', max_length=200, verbose_name='الشخص المعروف'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nkown_person_phone',
            field=models.CharField(default='', max_length=200, verbose_name='رقم الشخص المعروف'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nkown_person_relation',
            field=models.CharField(default='', max_length=200, verbose_name='مقدار علاقة الشخص بالمعرف'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(default='', max_length=200, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='person',
            name='represent',
            field=models.CharField(default='', max_length=200, verbose_name='الموقعية'),
        ),
    ]
